"""
AndyMark CAN Device API Constants for 2026.
"""

# General API Commands
SET_REPORT_PERIOD_API = 0x1B
RESET_REPORT_PERIOD_API = 0x1C
GET_JUNK_DATA = 0x20
RESTART_DEVICE_API = 0x07

# Encoder API
ENCODER_POSITION_API = 0x00
ENCODER_VELOCITY_API = 0x00
ENCODER_ZERO_CURRENT_POS = 0x20
ENCODER_RESET_OFFSET = 0x21
ENCODER_SET_OFFSET = 0x22
ENCODER_TELEMETRY_DATA = 0x23
ENCODER_STATUS_DATA = 0x24

# Motor Control API
MOTOR_CONTROL_SET_SPEED_API = 0x10
MOTOR_CONTROL_SET_BRAKE_COAST_API = 0x11

# Color Sensor API
COLORSENSOR_COLORDATA_API = 0x20
COLORSENSOR_PROX_TIMESTAMP_API = 0x21